package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/linki/pierone-cli/client/docker_registry_api_v1"
	"github.com/linki/pierone-cli/client/docker_registry_api_v2"
	"github.com/linki/pierone-cli/client/operations"
	"github.com/linki/pierone-cli/client/pier_one_api"
)

// Default pier one HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new pier one HTTP client.
func NewHTTPClient(formats strfmt.Registry) *PierOne {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost", "/", []string{"http"})
	return New(transport, formats)
}

// New creates a new pier one client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *PierOne {
	cli := new(PierOne)
	cli.Transport = transport

	cli.DockerRegistryAPIV1 = docker_registry_api_v1.New(transport, formats)

	cli.DockerRegistryAPIV2 = docker_registry_api_v2.New(transport, formats)

	cli.Operations = operations.New(transport, formats)

	cli.PierOneAPI = pier_one_api.New(transport, formats)

	return cli
}

// PierOne is a client for pier one
type PierOne struct {
	DockerRegistryAPIV1 *docker_registry_api_v1.Client

	DockerRegistryAPIV2 *docker_registry_api_v2.Client

	Operations *operations.Client

	PierOneAPI *pier_one_api.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *PierOne) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.DockerRegistryAPIV1.SetTransport(transport)

	c.DockerRegistryAPIV2.SetTransport(transport)

	c.Operations.SetTransport(transport)

	c.PierOneAPI.SetTransport(transport)

}
