package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV1PingReader is a Reader for the OrgZalandoStupsPieroneAPIV1Ping structure.
type OrgZalandoStupsPieroneAPIV1PingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV1PingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIV1PingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV1PingOK creates a OrgZalandoStupsPieroneAPIV1PingOK with default headers values
func NewOrgZalandoStupsPieroneAPIV1PingOK() *OrgZalandoStupsPieroneAPIV1PingOK {
	return &OrgZalandoStupsPieroneAPIV1PingOK{}
}

/*OrgZalandoStupsPieroneAPIV1PingOK handles this case with default header values.

Docker Registry v1 is available
*/
type OrgZalandoStupsPieroneAPIV1PingOK struct {
	XDockerRegistryVersion string

	Payload bool
}

func (o *OrgZalandoStupsPieroneAPIV1PingOK) Error() string {
	return fmt.Sprintf("[GET /v1/_ping][%d] orgZalandoStupsPieroneApiV1PingOK  %+v", 200, o.Payload)
}

func (o *OrgZalandoStupsPieroneAPIV1PingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header X-Docker-Registry-Version
	o.XDockerRegistryVersion = response.GetHeader("X-Docker-Registry-Version")

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
