package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgZalandoStupsPieroneAPIV1PutImageBinaryParams creates a new OrgZalandoStupsPieroneAPIV1PutImageBinaryParams object
// with the default values initialized.
func NewOrgZalandoStupsPieroneAPIV1PutImageBinaryParams() *OrgZalandoStupsPieroneAPIV1PutImageBinaryParams {
	var ()
	return &OrgZalandoStupsPieroneAPIV1PutImageBinaryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgZalandoStupsPieroneAPIV1PutImageBinaryParamsWithTimeout creates a new OrgZalandoStupsPieroneAPIV1PutImageBinaryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgZalandoStupsPieroneAPIV1PutImageBinaryParamsWithTimeout(timeout time.Duration) *OrgZalandoStupsPieroneAPIV1PutImageBinaryParams {
	var ()
	return &OrgZalandoStupsPieroneAPIV1PutImageBinaryParams{

		timeout: timeout,
	}
}

/*OrgZalandoStupsPieroneAPIV1PutImageBinaryParams contains all the parameters to send to the API endpoint
for the org zalando stups pierone api v1 put image binary operation typically these are written to a http.Request
*/
type OrgZalandoStupsPieroneAPIV1PutImageBinaryParams struct {

	/*Data*/
	Data interface{}
	/*Image*/
	Image string

	timeout time.Duration
}

// WithData adds the data to the org zalando stups pierone api v1 put image binary params
func (o *OrgZalandoStupsPieroneAPIV1PutImageBinaryParams) WithData(data interface{}) *OrgZalandoStupsPieroneAPIV1PutImageBinaryParams {
	o.Data = data
	return o
}

// WithImage adds the image to the org zalando stups pierone api v1 put image binary params
func (o *OrgZalandoStupsPieroneAPIV1PutImageBinaryParams) WithImage(image string) *OrgZalandoStupsPieroneAPIV1PutImageBinaryParams {
	o.Image = image
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *OrgZalandoStupsPieroneAPIV1PutImageBinaryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param image
	if err := r.SetPathParam("image", o.Image); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
