package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV1PostUsersReader is a Reader for the OrgZalandoStupsPieroneAPIV1PostUsers structure.
type OrgZalandoStupsPieroneAPIV1PostUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV1PostUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 401:
		result := NewOrgZalandoStupsPieroneAPIV1PostUsersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV1PostUsersUnauthorized creates a OrgZalandoStupsPieroneAPIV1PostUsersUnauthorized with default headers values
func NewOrgZalandoStupsPieroneAPIV1PostUsersUnauthorized() *OrgZalandoStupsPieroneAPIV1PostUsersUnauthorized {
	return &OrgZalandoStupsPieroneAPIV1PostUsersUnauthorized{}
}

/*OrgZalandoStupsPieroneAPIV1PostUsersUnauthorized handles this case with default header values.

Please use GET /v1/users
*/
type OrgZalandoStupsPieroneAPIV1PostUsersUnauthorized struct {
}

func (o *OrgZalandoStupsPieroneAPIV1PostUsersUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/users][%d] orgZalandoStupsPieroneApiV1PostUsersUnauthorized ", 401)
}

func (o *OrgZalandoStupsPieroneAPIV1PostUsersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
