package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV1LoginReader is a Reader for the OrgZalandoStupsPieroneAPIV1Login structure.
type OrgZalandoStupsPieroneAPIV1LoginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV1LoginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIV1LoginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV1LoginOK creates a OrgZalandoStupsPieroneAPIV1LoginOK with default headers values
func NewOrgZalandoStupsPieroneAPIV1LoginOK() *OrgZalandoStupsPieroneAPIV1LoginOK {
	return &OrgZalandoStupsPieroneAPIV1LoginOK{}
}

/*OrgZalandoStupsPieroneAPIV1LoginOK handles this case with default header values.

Login successful
*/
type OrgZalandoStupsPieroneAPIV1LoginOK struct {
}

func (o *OrgZalandoStupsPieroneAPIV1LoginOK) Error() string {
	return fmt.Sprintf("[GET /v1/users][%d] orgZalandoStupsPieroneApiV1LoginOK ", 200)
}

func (o *OrgZalandoStupsPieroneAPIV1LoginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
