package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV1GetImageBinaryReader is a Reader for the OrgZalandoStupsPieroneAPIV1GetImageBinary structure.
type OrgZalandoStupsPieroneAPIV1GetImageBinaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV1GetImageBinaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIV1GetImageBinaryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewOrgZalandoStupsPieroneAPIV1GetImageBinaryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV1GetImageBinaryOK creates a OrgZalandoStupsPieroneAPIV1GetImageBinaryOK with default headers values
func NewOrgZalandoStupsPieroneAPIV1GetImageBinaryOK() *OrgZalandoStupsPieroneAPIV1GetImageBinaryOK {
	return &OrgZalandoStupsPieroneAPIV1GetImageBinaryOK{}
}

/*OrgZalandoStupsPieroneAPIV1GetImageBinaryOK handles this case with default header values.

Return binary layer data
*/
type OrgZalandoStupsPieroneAPIV1GetImageBinaryOK struct {
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageBinaryOK) Error() string {
	return fmt.Sprintf("[GET /v1/images/{image}/layer][%d] orgZalandoStupsPieroneApiV1GetImageBinaryOK ", 200)
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageBinaryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOrgZalandoStupsPieroneAPIV1GetImageBinaryNotFound creates a OrgZalandoStupsPieroneAPIV1GetImageBinaryNotFound with default headers values
func NewOrgZalandoStupsPieroneAPIV1GetImageBinaryNotFound() *OrgZalandoStupsPieroneAPIV1GetImageBinaryNotFound {
	return &OrgZalandoStupsPieroneAPIV1GetImageBinaryNotFound{}
}

/*OrgZalandoStupsPieroneAPIV1GetImageBinaryNotFound handles this case with default header values.

Image layer does not exist
*/
type OrgZalandoStupsPieroneAPIV1GetImageBinaryNotFound struct {
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageBinaryNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/images/{image}/layer][%d] orgZalandoStupsPieroneApiV1GetImageBinaryNotFound ", 404)
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageBinaryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
