package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgZalandoStupsPieroneAPIV1GetImageForTagParams creates a new OrgZalandoStupsPieroneAPIV1GetImageForTagParams object
// with the default values initialized.
func NewOrgZalandoStupsPieroneAPIV1GetImageForTagParams() *OrgZalandoStupsPieroneAPIV1GetImageForTagParams {
	var ()
	return &OrgZalandoStupsPieroneAPIV1GetImageForTagParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgZalandoStupsPieroneAPIV1GetImageForTagParamsWithTimeout creates a new OrgZalandoStupsPieroneAPIV1GetImageForTagParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgZalandoStupsPieroneAPIV1GetImageForTagParamsWithTimeout(timeout time.Duration) *OrgZalandoStupsPieroneAPIV1GetImageForTagParams {
	var ()
	return &OrgZalandoStupsPieroneAPIV1GetImageForTagParams{

		timeout: timeout,
	}
}

/*OrgZalandoStupsPieroneAPIV1GetImageForTagParams contains all the parameters to send to the API endpoint
for the org zalando stups pierone api v1 get image for tag operation typically these are written to a http.Request
*/
type OrgZalandoStupsPieroneAPIV1GetImageForTagParams struct {

	/*Artifact*/
	Artifact string
	/*Name*/
	Name string
	/*Team*/
	Team string

	timeout time.Duration
}

// WithArtifact adds the artifact to the org zalando stups pierone api v1 get image for tag params
func (o *OrgZalandoStupsPieroneAPIV1GetImageForTagParams) WithArtifact(artifact string) *OrgZalandoStupsPieroneAPIV1GetImageForTagParams {
	o.Artifact = artifact
	return o
}

// WithName adds the name to the org zalando stups pierone api v1 get image for tag params
func (o *OrgZalandoStupsPieroneAPIV1GetImageForTagParams) WithName(name string) *OrgZalandoStupsPieroneAPIV1GetImageForTagParams {
	o.Name = name
	return o
}

// WithTeam adds the team to the org zalando stups pierone api v1 get image for tag params
func (o *OrgZalandoStupsPieroneAPIV1GetImageForTagParams) WithTeam(team string) *OrgZalandoStupsPieroneAPIV1GetImageForTagParams {
	o.Team = team
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *OrgZalandoStupsPieroneAPIV1GetImageForTagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param artifact
	if err := r.SetPathParam("artifact", o.Artifact); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
