package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgZalandoStupsPieroneAPIV1PutImageJSONParams creates a new OrgZalandoStupsPieroneAPIV1PutImageJSONParams object
// with the default values initialized.
func NewOrgZalandoStupsPieroneAPIV1PutImageJSONParams() *OrgZalandoStupsPieroneAPIV1PutImageJSONParams {
	var ()
	return &OrgZalandoStupsPieroneAPIV1PutImageJSONParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgZalandoStupsPieroneAPIV1PutImageJSONParamsWithTimeout creates a new OrgZalandoStupsPieroneAPIV1PutImageJSONParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgZalandoStupsPieroneAPIV1PutImageJSONParamsWithTimeout(timeout time.Duration) *OrgZalandoStupsPieroneAPIV1PutImageJSONParams {
	var ()
	return &OrgZalandoStupsPieroneAPIV1PutImageJSONParams{

		timeout: timeout,
	}
}

/*OrgZalandoStupsPieroneAPIV1PutImageJSONParams contains all the parameters to send to the API endpoint
for the org zalando stups pierone api v1 put image json operation typically these are written to a http.Request
*/
type OrgZalandoStupsPieroneAPIV1PutImageJSONParams struct {

	/*Image*/
	Image string
	/*Metadata*/
	Metadata interface{}

	timeout time.Duration
}

// WithImage adds the image to the org zalando stups pierone api v1 put image json params
func (o *OrgZalandoStupsPieroneAPIV1PutImageJSONParams) WithImage(image string) *OrgZalandoStupsPieroneAPIV1PutImageJSONParams {
	o.Image = image
	return o
}

// WithMetadata adds the metadata to the org zalando stups pierone api v1 put image json params
func (o *OrgZalandoStupsPieroneAPIV1PutImageJSONParams) WithMetadata(metadata interface{}) *OrgZalandoStupsPieroneAPIV1PutImageJSONParams {
	o.Metadata = metadata
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *OrgZalandoStupsPieroneAPIV1PutImageJSONParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param image
	if err := r.SetPathParam("image", o.Image); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Metadata); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
