package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgZalandoStupsPieroneAPIV1PingParams creates a new OrgZalandoStupsPieroneAPIV1PingParams object
// with the default values initialized.
func NewOrgZalandoStupsPieroneAPIV1PingParams() *OrgZalandoStupsPieroneAPIV1PingParams {

	return &OrgZalandoStupsPieroneAPIV1PingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgZalandoStupsPieroneAPIV1PingParamsWithTimeout creates a new OrgZalandoStupsPieroneAPIV1PingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgZalandoStupsPieroneAPIV1PingParamsWithTimeout(timeout time.Duration) *OrgZalandoStupsPieroneAPIV1PingParams {

	return &OrgZalandoStupsPieroneAPIV1PingParams{

		timeout: timeout,
	}
}

/*OrgZalandoStupsPieroneAPIV1PingParams contains all the parameters to send to the API endpoint
for the org zalando stups pierone api v1 ping operation typically these are written to a http.Request
*/
type OrgZalandoStupsPieroneAPIV1PingParams struct {
	timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *OrgZalandoStupsPieroneAPIV1PingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
