package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV1PutImagesReader is a Reader for the OrgZalandoStupsPieroneAPIV1PutImages structure.
type OrgZalandoStupsPieroneAPIV1PutImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV1PutImagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewOrgZalandoStupsPieroneAPIV1PutImagesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV1PutImagesNoContent creates a OrgZalandoStupsPieroneAPIV1PutImagesNoContent with default headers values
func NewOrgZalandoStupsPieroneAPIV1PutImagesNoContent() *OrgZalandoStupsPieroneAPIV1PutImagesNoContent {
	return &OrgZalandoStupsPieroneAPIV1PutImagesNoContent{}
}

/*OrgZalandoStupsPieroneAPIV1PutImagesNoContent handles this case with default header values.

No response was specified
*/
type OrgZalandoStupsPieroneAPIV1PutImagesNoContent struct {
}

func (o *OrgZalandoStupsPieroneAPIV1PutImagesNoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/{team}/{artifact}/images][%d] orgZalandoStupsPieroneApiV1PutImagesNoContent ", 204)
}

func (o *OrgZalandoStupsPieroneAPIV1PutImagesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
