package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgZalandoStupsPieroneAPIV1LoginParams creates a new OrgZalandoStupsPieroneAPIV1LoginParams object
// with the default values initialized.
func NewOrgZalandoStupsPieroneAPIV1LoginParams() *OrgZalandoStupsPieroneAPIV1LoginParams {

	return &OrgZalandoStupsPieroneAPIV1LoginParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgZalandoStupsPieroneAPIV1LoginParamsWithTimeout creates a new OrgZalandoStupsPieroneAPIV1LoginParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgZalandoStupsPieroneAPIV1LoginParamsWithTimeout(timeout time.Duration) *OrgZalandoStupsPieroneAPIV1LoginParams {

	return &OrgZalandoStupsPieroneAPIV1LoginParams{

		timeout: timeout,
	}
}

/*OrgZalandoStupsPieroneAPIV1LoginParams contains all the parameters to send to the API endpoint
for the org zalando stups pierone api v1 login operation typically these are written to a http.Request
*/
type OrgZalandoStupsPieroneAPIV1LoginParams struct {
	timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *OrgZalandoStupsPieroneAPIV1LoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
