package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV1GetImageForTagReader is a Reader for the OrgZalandoStupsPieroneAPIV1GetImageForTag structure.
type OrgZalandoStupsPieroneAPIV1GetImageForTagReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV1GetImageForTagReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIV1GetImageForTagOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewOrgZalandoStupsPieroneAPIV1GetImageForTagNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV1GetImageForTagOK creates a OrgZalandoStupsPieroneAPIV1GetImageForTagOK with default headers values
func NewOrgZalandoStupsPieroneAPIV1GetImageForTagOK() *OrgZalandoStupsPieroneAPIV1GetImageForTagOK {
	return &OrgZalandoStupsPieroneAPIV1GetImageForTagOK{}
}

/*OrgZalandoStupsPieroneAPIV1GetImageForTagOK handles this case with default header values.

Tag exists
*/
type OrgZalandoStupsPieroneAPIV1GetImageForTagOK struct {
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageForTagOK) Error() string {
	return fmt.Sprintf("[GET /v1/repositories/{team}/{artifact}/tags/{name}][%d] orgZalandoStupsPieroneApiV1GetImageForTagOK ", 200)
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageForTagOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOrgZalandoStupsPieroneAPIV1GetImageForTagNotFound creates a OrgZalandoStupsPieroneAPIV1GetImageForTagNotFound with default headers values
func NewOrgZalandoStupsPieroneAPIV1GetImageForTagNotFound() *OrgZalandoStupsPieroneAPIV1GetImageForTagNotFound {
	return &OrgZalandoStupsPieroneAPIV1GetImageForTagNotFound{}
}

/*OrgZalandoStupsPieroneAPIV1GetImageForTagNotFound handles this case with default header values.

Tag does not exist
*/
type OrgZalandoStupsPieroneAPIV1GetImageForTagNotFound struct {
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageForTagNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/repositories/{team}/{artifact}/tags/{name}][%d] orgZalandoStupsPieroneApiV1GetImageForTagNotFound ", 404)
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageForTagNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
