package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV1GetImagesReader is a Reader for the OrgZalandoStupsPieroneAPIV1GetImages structure.
type OrgZalandoStupsPieroneAPIV1GetImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV1GetImagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIV1GetImagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV1GetImagesOK creates a OrgZalandoStupsPieroneAPIV1GetImagesOK with default headers values
func NewOrgZalandoStupsPieroneAPIV1GetImagesOK() *OrgZalandoStupsPieroneAPIV1GetImagesOK {
	return &OrgZalandoStupsPieroneAPIV1GetImagesOK{}
}

/*OrgZalandoStupsPieroneAPIV1GetImagesOK handles this case with default header values.

No response was specified
*/
type OrgZalandoStupsPieroneAPIV1GetImagesOK struct {
}

func (o *OrgZalandoStupsPieroneAPIV1GetImagesOK) Error() string {
	return fmt.Sprintf("[GET /v1/repositories/{team}/{artifact}/images][%d] orgZalandoStupsPieroneApiV1GetImagesOK ", 200)
}

func (o *OrgZalandoStupsPieroneAPIV1GetImagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
