package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV1PutImageBinaryReader is a Reader for the OrgZalandoStupsPieroneAPIV1PutImageBinary structure.
type OrgZalandoStupsPieroneAPIV1PutImageBinaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV1PutImageBinaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIV1PutImageBinaryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV1PutImageBinaryOK creates a OrgZalandoStupsPieroneAPIV1PutImageBinaryOK with default headers values
func NewOrgZalandoStupsPieroneAPIV1PutImageBinaryOK() *OrgZalandoStupsPieroneAPIV1PutImageBinaryOK {
	return &OrgZalandoStupsPieroneAPIV1PutImageBinaryOK{}
}

/*OrgZalandoStupsPieroneAPIV1PutImageBinaryOK handles this case with default header values.

Image layer data was stored successfully
*/
type OrgZalandoStupsPieroneAPIV1PutImageBinaryOK struct {
}

func (o *OrgZalandoStupsPieroneAPIV1PutImageBinaryOK) Error() string {
	return fmt.Sprintf("[PUT /v1/images/{image}/layer][%d] orgZalandoStupsPieroneApiV1PutImageBinaryOK ", 200)
}

func (o *OrgZalandoStupsPieroneAPIV1PutImageBinaryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
