package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV1PutImageChecksumReader is a Reader for the OrgZalandoStupsPieroneAPIV1PutImageChecksum structure.
type OrgZalandoStupsPieroneAPIV1PutImageChecksumReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV1PutImageChecksumReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIV1PutImageChecksumOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV1PutImageChecksumOK creates a OrgZalandoStupsPieroneAPIV1PutImageChecksumOK with default headers values
func NewOrgZalandoStupsPieroneAPIV1PutImageChecksumOK() *OrgZalandoStupsPieroneAPIV1PutImageChecksumOK {
	return &OrgZalandoStupsPieroneAPIV1PutImageChecksumOK{}
}

/*OrgZalandoStupsPieroneAPIV1PutImageChecksumOK handles this case with default header values.

No response was specified
*/
type OrgZalandoStupsPieroneAPIV1PutImageChecksumOK struct {
}

func (o *OrgZalandoStupsPieroneAPIV1PutImageChecksumOK) Error() string {
	return fmt.Sprintf("[PUT /v1/images/{image}/checksum][%d] orgZalandoStupsPieroneApiV1PutImageChecksumOK ", 200)
}

func (o *OrgZalandoStupsPieroneAPIV1PutImageChecksumOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
