package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV1GetImageJSONReader is a Reader for the OrgZalandoStupsPieroneAPIV1GetImageJSON structure.
type OrgZalandoStupsPieroneAPIV1GetImageJSONReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV1GetImageJSONReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIV1GetImageJSONOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewOrgZalandoStupsPieroneAPIV1GetImageJSONNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV1GetImageJSONOK creates a OrgZalandoStupsPieroneAPIV1GetImageJSONOK with default headers values
func NewOrgZalandoStupsPieroneAPIV1GetImageJSONOK() *OrgZalandoStupsPieroneAPIV1GetImageJSONOK {
	return &OrgZalandoStupsPieroneAPIV1GetImageJSONOK{}
}

/*OrgZalandoStupsPieroneAPIV1GetImageJSONOK handles this case with default header values.

No response was specified
*/
type OrgZalandoStupsPieroneAPIV1GetImageJSONOK struct {
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageJSONOK) Error() string {
	return fmt.Sprintf("[GET /v1/images/{image}/json][%d] orgZalandoStupsPieroneApiV1GetImageJsonOK ", 200)
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageJSONOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOrgZalandoStupsPieroneAPIV1GetImageJSONNotFound creates a OrgZalandoStupsPieroneAPIV1GetImageJSONNotFound with default headers values
func NewOrgZalandoStupsPieroneAPIV1GetImageJSONNotFound() *OrgZalandoStupsPieroneAPIV1GetImageJSONNotFound {
	return &OrgZalandoStupsPieroneAPIV1GetImageJSONNotFound{}
}

/*OrgZalandoStupsPieroneAPIV1GetImageJSONNotFound handles this case with default header values.

Image does not exist
*/
type OrgZalandoStupsPieroneAPIV1GetImageJSONNotFound struct {
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageJSONNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/images/{image}/json][%d] orgZalandoStupsPieroneApiV1GetImageJsonNotFound ", 404)
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageJSONNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
