package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV1GetImageAncestryReader is a Reader for the OrgZalandoStupsPieroneAPIV1GetImageAncestry structure.
type OrgZalandoStupsPieroneAPIV1GetImageAncestryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV1GetImageAncestryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIV1GetImageAncestryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewOrgZalandoStupsPieroneAPIV1GetImageAncestryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV1GetImageAncestryOK creates a OrgZalandoStupsPieroneAPIV1GetImageAncestryOK with default headers values
func NewOrgZalandoStupsPieroneAPIV1GetImageAncestryOK() *OrgZalandoStupsPieroneAPIV1GetImageAncestryOK {
	return &OrgZalandoStupsPieroneAPIV1GetImageAncestryOK{}
}

/*OrgZalandoStupsPieroneAPIV1GetImageAncestryOK handles this case with default header values.

Return list of image IDs
*/
type OrgZalandoStupsPieroneAPIV1GetImageAncestryOK struct {
	Payload []string
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageAncestryOK) Error() string {
	return fmt.Sprintf("[GET /v1/images/{image}/ancestry][%d] orgZalandoStupsPieroneApiV1GetImageAncestryOK  %+v", 200, o.Payload)
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageAncestryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOrgZalandoStupsPieroneAPIV1GetImageAncestryNotFound creates a OrgZalandoStupsPieroneAPIV1GetImageAncestryNotFound with default headers values
func NewOrgZalandoStupsPieroneAPIV1GetImageAncestryNotFound() *OrgZalandoStupsPieroneAPIV1GetImageAncestryNotFound {
	return &OrgZalandoStupsPieroneAPIV1GetImageAncestryNotFound{}
}

/*OrgZalandoStupsPieroneAPIV1GetImageAncestryNotFound handles this case with default header values.

Image ID does not exist
*/
type OrgZalandoStupsPieroneAPIV1GetImageAncestryNotFound struct {
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageAncestryNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/images/{image}/ancestry][%d] orgZalandoStupsPieroneApiV1GetImageAncestryNotFound ", 404)
}

func (o *OrgZalandoStupsPieroneAPIV1GetImageAncestryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
