package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV1PutImageJSONReader is a Reader for the OrgZalandoStupsPieroneAPIV1PutImageJSON structure.
type OrgZalandoStupsPieroneAPIV1PutImageJSONReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV1PutImageJSONReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIV1PutImageJSONOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV1PutImageJSONOK creates a OrgZalandoStupsPieroneAPIV1PutImageJSONOK with default headers values
func NewOrgZalandoStupsPieroneAPIV1PutImageJSONOK() *OrgZalandoStupsPieroneAPIV1PutImageJSONOK {
	return &OrgZalandoStupsPieroneAPIV1PutImageJSONOK{}
}

/*OrgZalandoStupsPieroneAPIV1PutImageJSONOK handles this case with default header values.

Image JSON was stored successfully
*/
type OrgZalandoStupsPieroneAPIV1PutImageJSONOK struct {
}

func (o *OrgZalandoStupsPieroneAPIV1PutImageJSONOK) Error() string {
	return fmt.Sprintf("[PUT /v1/images/{image}/json][%d] orgZalandoStupsPieroneApiV1PutImageJsonOK ", 200)
}

func (o *OrgZalandoStupsPieroneAPIV1PutImageJSONOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
