package docker_registry_api_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV1GetTagsReader is a Reader for the OrgZalandoStupsPieroneAPIV1GetTags structure.
type OrgZalandoStupsPieroneAPIV1GetTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV1GetTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIV1GetTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewOrgZalandoStupsPieroneAPIV1GetTagsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV1GetTagsOK creates a OrgZalandoStupsPieroneAPIV1GetTagsOK with default headers values
func NewOrgZalandoStupsPieroneAPIV1GetTagsOK() *OrgZalandoStupsPieroneAPIV1GetTagsOK {
	return &OrgZalandoStupsPieroneAPIV1GetTagsOK{}
}

/*OrgZalandoStupsPieroneAPIV1GetTagsOK handles this case with default header values.

Map of tags to image IDs
*/
type OrgZalandoStupsPieroneAPIV1GetTagsOK struct {
}

func (o *OrgZalandoStupsPieroneAPIV1GetTagsOK) Error() string {
	return fmt.Sprintf("[GET /v1/repositories/{team}/{artifact}/tags][%d] orgZalandoStupsPieroneApiV1GetTagsOK ", 200)
}

func (o *OrgZalandoStupsPieroneAPIV1GetTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOrgZalandoStupsPieroneAPIV1GetTagsNotFound creates a OrgZalandoStupsPieroneAPIV1GetTagsNotFound with default headers values
func NewOrgZalandoStupsPieroneAPIV1GetTagsNotFound() *OrgZalandoStupsPieroneAPIV1GetTagsNotFound {
	return &OrgZalandoStupsPieroneAPIV1GetTagsNotFound{}
}

/*OrgZalandoStupsPieroneAPIV1GetTagsNotFound handles this case with default header values.

Repository/tags not found
*/
type OrgZalandoStupsPieroneAPIV1GetTagsNotFound struct {
}

func (o *OrgZalandoStupsPieroneAPIV1GetTagsNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/repositories/{team}/{artifact}/tags][%d] orgZalandoStupsPieroneApiV1GetTagsNotFound ", 404)
}

func (o *OrgZalandoStupsPieroneAPIV1GetTagsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
