package docker_registry_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgZalandoStupsPieroneAPIV2HeadBlobParams creates a new OrgZalandoStupsPieroneAPIV2HeadBlobParams object
// with the default values initialized.
func NewOrgZalandoStupsPieroneAPIV2HeadBlobParams() *OrgZalandoStupsPieroneAPIV2HeadBlobParams {
	var ()
	return &OrgZalandoStupsPieroneAPIV2HeadBlobParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgZalandoStupsPieroneAPIV2HeadBlobParamsWithTimeout creates a new OrgZalandoStupsPieroneAPIV2HeadBlobParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgZalandoStupsPieroneAPIV2HeadBlobParamsWithTimeout(timeout time.Duration) *OrgZalandoStupsPieroneAPIV2HeadBlobParams {
	var ()
	return &OrgZalandoStupsPieroneAPIV2HeadBlobParams{

		timeout: timeout,
	}
}

/*OrgZalandoStupsPieroneAPIV2HeadBlobParams contains all the parameters to send to the API endpoint
for the org zalando stups pierone api v2 head blob operation typically these are written to a http.Request
*/
type OrgZalandoStupsPieroneAPIV2HeadBlobParams struct {

	/*Artifact*/
	Artifact string
	/*Digest
	  Layer digest as described on https://docs.docker.com/registry/spec/api/#pushing-an-image

	*/
	Digest string
	/*Team*/
	Team string

	timeout time.Duration
}

// WithArtifact adds the artifact to the org zalando stups pierone api v2 head blob params
func (o *OrgZalandoStupsPieroneAPIV2HeadBlobParams) WithArtifact(artifact string) *OrgZalandoStupsPieroneAPIV2HeadBlobParams {
	o.Artifact = artifact
	return o
}

// WithDigest adds the digest to the org zalando stups pierone api v2 head blob params
func (o *OrgZalandoStupsPieroneAPIV2HeadBlobParams) WithDigest(digest string) *OrgZalandoStupsPieroneAPIV2HeadBlobParams {
	o.Digest = digest
	return o
}

// WithTeam adds the team to the org zalando stups pierone api v2 head blob params
func (o *OrgZalandoStupsPieroneAPIV2HeadBlobParams) WithTeam(team string) *OrgZalandoStupsPieroneAPIV2HeadBlobParams {
	o.Team = team
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *OrgZalandoStupsPieroneAPIV2HeadBlobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param artifact
	if err := r.SetPathParam("artifact", o.Artifact); err != nil {
		return err
	}

	// path param digest
	if err := r.SetPathParam("digest", o.Digest); err != nil {
		return err
	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
