package docker_registry_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV2PostUploadReader is a Reader for the OrgZalandoStupsPieroneAPIV2PostUpload structure.
type OrgZalandoStupsPieroneAPIV2PostUploadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV2PostUploadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 202:
		result := NewOrgZalandoStupsPieroneAPIV2PostUploadAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV2PostUploadAccepted creates a OrgZalandoStupsPieroneAPIV2PostUploadAccepted with default headers values
func NewOrgZalandoStupsPieroneAPIV2PostUploadAccepted() *OrgZalandoStupsPieroneAPIV2PostUploadAccepted {
	return &OrgZalandoStupsPieroneAPIV2PostUploadAccepted{}
}

/*OrgZalandoStupsPieroneAPIV2PostUploadAccepted handles this case with default header values.

upload accepted
*/
type OrgZalandoStupsPieroneAPIV2PostUploadAccepted struct {
}

func (o *OrgZalandoStupsPieroneAPIV2PostUploadAccepted) Error() string {
	return fmt.Sprintf("[POST /v2/{team}/{artifact}/blobs/uploads/][%d] orgZalandoStupsPieroneApiV2PostUploadAccepted ", 202)
}

func (o *OrgZalandoStupsPieroneAPIV2PostUploadAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
