package docker_registry_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV2GetManifestReader is a Reader for the OrgZalandoStupsPieroneAPIV2GetManifest structure.
type OrgZalandoStupsPieroneAPIV2GetManifestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV2GetManifestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIV2GetManifestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV2GetManifestOK creates a OrgZalandoStupsPieroneAPIV2GetManifestOK with default headers values
func NewOrgZalandoStupsPieroneAPIV2GetManifestOK() *OrgZalandoStupsPieroneAPIV2GetManifestOK {
	return &OrgZalandoStupsPieroneAPIV2GetManifestOK{}
}

/*OrgZalandoStupsPieroneAPIV2GetManifestOK handles this case with default header values.

OK
*/
type OrgZalandoStupsPieroneAPIV2GetManifestOK struct {
}

func (o *OrgZalandoStupsPieroneAPIV2GetManifestOK) Error() string {
	return fmt.Sprintf("[GET /v2/{team}/{artifact}/manifests/{name}][%d] orgZalandoStupsPieroneApiV2GetManifestOK ", 200)
}

func (o *OrgZalandoStupsPieroneAPIV2GetManifestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
