package docker_registry_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV2GetBlobReader is a Reader for the OrgZalandoStupsPieroneAPIV2GetBlob structure.
type OrgZalandoStupsPieroneAPIV2GetBlobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV2GetBlobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIV2GetBlobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV2GetBlobOK creates a OrgZalandoStupsPieroneAPIV2GetBlobOK with default headers values
func NewOrgZalandoStupsPieroneAPIV2GetBlobOK() *OrgZalandoStupsPieroneAPIV2GetBlobOK {
	return &OrgZalandoStupsPieroneAPIV2GetBlobOK{}
}

/*OrgZalandoStupsPieroneAPIV2GetBlobOK handles this case with default header values.

exists
*/
type OrgZalandoStupsPieroneAPIV2GetBlobOK struct {
}

func (o *OrgZalandoStupsPieroneAPIV2GetBlobOK) Error() string {
	return fmt.Sprintf("[GET /v2/{team}/{artifact}/blobs/{digest}][%d] orgZalandoStupsPieroneApiV2GetBlobOK ", 200)
}

func (o *OrgZalandoStupsPieroneAPIV2GetBlobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
