package docker_registry_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV2PutUploadReader is a Reader for the OrgZalandoStupsPieroneAPIV2PutUpload structure.
type OrgZalandoStupsPieroneAPIV2PutUploadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV2PutUploadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewOrgZalandoStupsPieroneAPIV2PutUploadCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV2PutUploadCreated creates a OrgZalandoStupsPieroneAPIV2PutUploadCreated with default headers values
func NewOrgZalandoStupsPieroneAPIV2PutUploadCreated() *OrgZalandoStupsPieroneAPIV2PutUploadCreated {
	return &OrgZalandoStupsPieroneAPIV2PutUploadCreated{}
}

/*OrgZalandoStupsPieroneAPIV2PutUploadCreated handles this case with default header values.

upload accepted
*/
type OrgZalandoStupsPieroneAPIV2PutUploadCreated struct {
}

func (o *OrgZalandoStupsPieroneAPIV2PutUploadCreated) Error() string {
	return fmt.Sprintf("[PUT /v2/{team}/{artifact}/blobs/uploads/{uuid}][%d] orgZalandoStupsPieroneApiV2PutUploadCreated ", 201)
}

func (o *OrgZalandoStupsPieroneAPIV2PutUploadCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
