package docker_registry_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgZalandoStupsPieroneAPIV2ListTagsParams creates a new OrgZalandoStupsPieroneAPIV2ListTagsParams object
// with the default values initialized.
func NewOrgZalandoStupsPieroneAPIV2ListTagsParams() *OrgZalandoStupsPieroneAPIV2ListTagsParams {
	var ()
	return &OrgZalandoStupsPieroneAPIV2ListTagsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgZalandoStupsPieroneAPIV2ListTagsParamsWithTimeout creates a new OrgZalandoStupsPieroneAPIV2ListTagsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgZalandoStupsPieroneAPIV2ListTagsParamsWithTimeout(timeout time.Duration) *OrgZalandoStupsPieroneAPIV2ListTagsParams {
	var ()
	return &OrgZalandoStupsPieroneAPIV2ListTagsParams{

		timeout: timeout,
	}
}

/*OrgZalandoStupsPieroneAPIV2ListTagsParams contains all the parameters to send to the API endpoint
for the org zalando stups pierone api v2 list tags operation typically these are written to a http.Request
*/
type OrgZalandoStupsPieroneAPIV2ListTagsParams struct {

	/*Artifact*/
	Artifact string
	/*Team*/
	Team string

	timeout time.Duration
}

// WithArtifact adds the artifact to the org zalando stups pierone api v2 list tags params
func (o *OrgZalandoStupsPieroneAPIV2ListTagsParams) WithArtifact(artifact string) *OrgZalandoStupsPieroneAPIV2ListTagsParams {
	o.Artifact = artifact
	return o
}

// WithTeam adds the team to the org zalando stups pierone api v2 list tags params
func (o *OrgZalandoStupsPieroneAPIV2ListTagsParams) WithTeam(team string) *OrgZalandoStupsPieroneAPIV2ListTagsParams {
	o.Team = team
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *OrgZalandoStupsPieroneAPIV2ListTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param artifact
	if err := r.SetPathParam("artifact", o.Artifact); err != nil {
		return err
	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
