package docker_registry_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV2ListRepositoriesReader is a Reader for the OrgZalandoStupsPieroneAPIV2ListRepositories structure.
type OrgZalandoStupsPieroneAPIV2ListRepositoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV2ListRepositoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIV2ListRepositoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV2ListRepositoriesOK creates a OrgZalandoStupsPieroneAPIV2ListRepositoriesOK with default headers values
func NewOrgZalandoStupsPieroneAPIV2ListRepositoriesOK() *OrgZalandoStupsPieroneAPIV2ListRepositoriesOK {
	return &OrgZalandoStupsPieroneAPIV2ListRepositoriesOK{}
}

/*OrgZalandoStupsPieroneAPIV2ListRepositoriesOK handles this case with default header values.

list of repos
*/
type OrgZalandoStupsPieroneAPIV2ListRepositoriesOK struct {
	Payload OrgZalandoStupsPieroneAPIV2ListRepositoriesOKBodyBody
}

func (o *OrgZalandoStupsPieroneAPIV2ListRepositoriesOK) Error() string {
	return fmt.Sprintf("[GET /v2/_catalog][%d] orgZalandoStupsPieroneApiV2ListRepositoriesOK  %+v", 200, o.Payload)
}

func (o *OrgZalandoStupsPieroneAPIV2ListRepositoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*OrgZalandoStupsPieroneAPIV2ListRepositoriesOKBodyBody org zalando stups pierone API v2 list repositories o k body body

swagger:model OrgZalandoStupsPieroneAPIV2ListRepositoriesOKBodyBody
*/
type OrgZalandoStupsPieroneAPIV2ListRepositoriesOKBodyBody struct {

	/* repositories

	Required: true
	*/
	Repositories []string `json:"repositories"`
}

// Validate validates this org zalando stups pierone API v2 list repositories o k body body
func (o *OrgZalandoStupsPieroneAPIV2ListRepositoriesOKBodyBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRepositories(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *OrgZalandoStupsPieroneAPIV2ListRepositoriesOKBodyBody) validateRepositories(formats strfmt.Registry) error {

	if err := validate.Required("orgZalandoStupsPieroneApiV2ListRepositoriesOK"+"."+"repositories", "body", o.Repositories); err != nil {
		return err
	}

	return nil
}
