package docker_registry_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgZalandoStupsPieroneAPIV2GetBlobParams creates a new OrgZalandoStupsPieroneAPIV2GetBlobParams object
// with the default values initialized.
func NewOrgZalandoStupsPieroneAPIV2GetBlobParams() *OrgZalandoStupsPieroneAPIV2GetBlobParams {
	var ()
	return &OrgZalandoStupsPieroneAPIV2GetBlobParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgZalandoStupsPieroneAPIV2GetBlobParamsWithTimeout creates a new OrgZalandoStupsPieroneAPIV2GetBlobParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgZalandoStupsPieroneAPIV2GetBlobParamsWithTimeout(timeout time.Duration) *OrgZalandoStupsPieroneAPIV2GetBlobParams {
	var ()
	return &OrgZalandoStupsPieroneAPIV2GetBlobParams{

		timeout: timeout,
	}
}

/*OrgZalandoStupsPieroneAPIV2GetBlobParams contains all the parameters to send to the API endpoint
for the org zalando stups pierone api v2 get blob operation typically these are written to a http.Request
*/
type OrgZalandoStupsPieroneAPIV2GetBlobParams struct {

	/*Artifact*/
	Artifact string
	/*Digest
	  Layer digest as described on https://docs.docker.com/registry/spec/api/#pushing-an-image

	*/
	Digest string
	/*Team*/
	Team string

	timeout time.Duration
}

// WithArtifact adds the artifact to the org zalando stups pierone api v2 get blob params
func (o *OrgZalandoStupsPieroneAPIV2GetBlobParams) WithArtifact(artifact string) *OrgZalandoStupsPieroneAPIV2GetBlobParams {
	o.Artifact = artifact
	return o
}

// WithDigest adds the digest to the org zalando stups pierone api v2 get blob params
func (o *OrgZalandoStupsPieroneAPIV2GetBlobParams) WithDigest(digest string) *OrgZalandoStupsPieroneAPIV2GetBlobParams {
	o.Digest = digest
	return o
}

// WithTeam adds the team to the org zalando stups pierone api v2 get blob params
func (o *OrgZalandoStupsPieroneAPIV2GetBlobParams) WithTeam(team string) *OrgZalandoStupsPieroneAPIV2GetBlobParams {
	o.Team = team
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *OrgZalandoStupsPieroneAPIV2GetBlobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param artifact
	if err := r.SetPathParam("artifact", o.Artifact); err != nil {
		return err
	}

	// path param digest
	if err := r.SetPathParam("digest", o.Digest); err != nil {
		return err
	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
