package docker_registry_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIV2PatchUploadReader is a Reader for the OrgZalandoStupsPieroneAPIV2PatchUpload structure.
type OrgZalandoStupsPieroneAPIV2PatchUploadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIV2PatchUploadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 202:
		result := NewOrgZalandoStupsPieroneAPIV2PatchUploadAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIV2PatchUploadAccepted creates a OrgZalandoStupsPieroneAPIV2PatchUploadAccepted with default headers values
func NewOrgZalandoStupsPieroneAPIV2PatchUploadAccepted() *OrgZalandoStupsPieroneAPIV2PatchUploadAccepted {
	return &OrgZalandoStupsPieroneAPIV2PatchUploadAccepted{}
}

/*OrgZalandoStupsPieroneAPIV2PatchUploadAccepted handles this case with default header values.

upload accepted
*/
type OrgZalandoStupsPieroneAPIV2PatchUploadAccepted struct {
}

func (o *OrgZalandoStupsPieroneAPIV2PatchUploadAccepted) Error() string {
	return fmt.Sprintf("[PATCH /v2/{team}/{artifact}/blobs/uploads/{uuid}][%d] orgZalandoStupsPieroneApiV2PatchUploadAccepted ", 202)
}

func (o *OrgZalandoStupsPieroneAPIV2PatchUploadAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
