package pier_one_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIReadArtifactsReader is a Reader for the OrgZalandoStupsPieroneAPIReadArtifacts structure.
type OrgZalandoStupsPieroneAPIReadArtifactsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIReadArtifactsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIReadArtifactsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIReadArtifactsOK creates a OrgZalandoStupsPieroneAPIReadArtifactsOK with default headers values
func NewOrgZalandoStupsPieroneAPIReadArtifactsOK() *OrgZalandoStupsPieroneAPIReadArtifactsOK {
	return &OrgZalandoStupsPieroneAPIReadArtifactsOK{}
}

/*OrgZalandoStupsPieroneAPIReadArtifactsOK handles this case with default header values.

Return list of artifact IDs
*/
type OrgZalandoStupsPieroneAPIReadArtifactsOK struct {
	Payload []string
}

func (o *OrgZalandoStupsPieroneAPIReadArtifactsOK) Error() string {
	return fmt.Sprintf("[GET /teams/{team}/artifacts][%d] orgZalandoStupsPieroneApiReadArtifactsOK  %+v", 200, o.Payload)
}

func (o *OrgZalandoStupsPieroneAPIReadArtifactsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
