package pier_one_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/linki/pierone-cli/models"
)

// OrgZalandoStupsPieroneAPIGetScmSourceReader is a Reader for the OrgZalandoStupsPieroneAPIGetScmSource structure.
type OrgZalandoStupsPieroneAPIGetScmSourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIGetScmSourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIGetScmSourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIGetScmSourceOK creates a OrgZalandoStupsPieroneAPIGetScmSourceOK with default headers values
func NewOrgZalandoStupsPieroneAPIGetScmSourceOK() *OrgZalandoStupsPieroneAPIGetScmSourceOK {
	return &OrgZalandoStupsPieroneAPIGetScmSourceOK{}
}

/*OrgZalandoStupsPieroneAPIGetScmSourceOK handles this case with default header values.

Return scm-source.json
*/
type OrgZalandoStupsPieroneAPIGetScmSourceOK struct {
	Payload *models.ScmSourceInformation
}

func (o *OrgZalandoStupsPieroneAPIGetScmSourceOK) Error() string {
	return fmt.Sprintf("[GET /teams/{team}/artifacts/{artifact}/tags/{tag}/scm-source][%d] orgZalandoStupsPieroneApiGetScmSourceOK  %+v", 200, o.Payload)
}

func (o *OrgZalandoStupsPieroneAPIGetScmSourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ScmSourceInformation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
