package pier_one_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgZalandoStupsPieroneAPIReadArtifactsParams creates a new OrgZalandoStupsPieroneAPIReadArtifactsParams object
// with the default values initialized.
func NewOrgZalandoStupsPieroneAPIReadArtifactsParams() *OrgZalandoStupsPieroneAPIReadArtifactsParams {
	var ()
	return &OrgZalandoStupsPieroneAPIReadArtifactsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgZalandoStupsPieroneAPIReadArtifactsParamsWithTimeout creates a new OrgZalandoStupsPieroneAPIReadArtifactsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgZalandoStupsPieroneAPIReadArtifactsParamsWithTimeout(timeout time.Duration) *OrgZalandoStupsPieroneAPIReadArtifactsParams {
	var ()
	return &OrgZalandoStupsPieroneAPIReadArtifactsParams{

		timeout: timeout,
	}
}

/*OrgZalandoStupsPieroneAPIReadArtifactsParams contains all the parameters to send to the API endpoint
for the org zalando stups pierone api read artifacts operation typically these are written to a http.Request
*/
type OrgZalandoStupsPieroneAPIReadArtifactsParams struct {

	/*Team*/
	Team string

	timeout time.Duration
}

// WithTeam adds the team to the org zalando stups pierone api read artifacts params
func (o *OrgZalandoStupsPieroneAPIReadArtifactsParams) WithTeam(team string) *OrgZalandoStupsPieroneAPIReadArtifactsParams {
	o.Team = team
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *OrgZalandoStupsPieroneAPIReadArtifactsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
