package pier_one_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/linki/pierone-cli/models"
)

// OrgZalandoStupsPieroneAPIListTagsForImageReader is a Reader for the OrgZalandoStupsPieroneAPIListTagsForImage structure.
type OrgZalandoStupsPieroneAPIListTagsForImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIListTagsForImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIListTagsForImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewOrgZalandoStupsPieroneAPIListTagsForImageNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 412:
		result := NewOrgZalandoStupsPieroneAPIListTagsForImagePreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIListTagsForImageOK creates a OrgZalandoStupsPieroneAPIListTagsForImageOK with default headers values
func NewOrgZalandoStupsPieroneAPIListTagsForImageOK() *OrgZalandoStupsPieroneAPIListTagsForImageOK {
	return &OrgZalandoStupsPieroneAPIListTagsForImageOK{}
}

/*OrgZalandoStupsPieroneAPIListTagsForImageOK handles this case with default header values.

Return tags
*/
type OrgZalandoStupsPieroneAPIListTagsForImageOK struct {
	Payload []*models.TagInformation
}

func (o *OrgZalandoStupsPieroneAPIListTagsForImageOK) Error() string {
	return fmt.Sprintf("[GET /tags/{image}][%d] orgZalandoStupsPieroneApiListTagsForImageOK  %+v", 200, o.Payload)
}

func (o *OrgZalandoStupsPieroneAPIListTagsForImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOrgZalandoStupsPieroneAPIListTagsForImageNotFound creates a OrgZalandoStupsPieroneAPIListTagsForImageNotFound with default headers values
func NewOrgZalandoStupsPieroneAPIListTagsForImageNotFound() *OrgZalandoStupsPieroneAPIListTagsForImageNotFound {
	return &OrgZalandoStupsPieroneAPIListTagsForImageNotFound{}
}

/*OrgZalandoStupsPieroneAPIListTagsForImageNotFound handles this case with default header values.

Prefix does not match any image id
*/
type OrgZalandoStupsPieroneAPIListTagsForImageNotFound struct {
}

func (o *OrgZalandoStupsPieroneAPIListTagsForImageNotFound) Error() string {
	return fmt.Sprintf("[GET /tags/{image}][%d] orgZalandoStupsPieroneApiListTagsForImageNotFound ", 404)
}

func (o *OrgZalandoStupsPieroneAPIListTagsForImageNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOrgZalandoStupsPieroneAPIListTagsForImagePreconditionFailed creates a OrgZalandoStupsPieroneAPIListTagsForImagePreconditionFailed with default headers values
func NewOrgZalandoStupsPieroneAPIListTagsForImagePreconditionFailed() *OrgZalandoStupsPieroneAPIListTagsForImagePreconditionFailed {
	return &OrgZalandoStupsPieroneAPIListTagsForImagePreconditionFailed{}
}

/*OrgZalandoStupsPieroneAPIListTagsForImagePreconditionFailed handles this case with default header values.

Prefix matches more than one image id
*/
type OrgZalandoStupsPieroneAPIListTagsForImagePreconditionFailed struct {
}

func (o *OrgZalandoStupsPieroneAPIListTagsForImagePreconditionFailed) Error() string {
	return fmt.Sprintf("[GET /tags/{image}][%d] orgZalandoStupsPieroneApiListTagsForImagePreconditionFailed ", 412)
}

func (o *OrgZalandoStupsPieroneAPIListTagsForImagePreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
