package pier_one_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/linki/pierone-cli/models"
)

// OrgZalandoStupsPieroneAPIGetTeamStatsReader is a Reader for the OrgZalandoStupsPieroneAPIGetTeamStats structure.
type OrgZalandoStupsPieroneAPIGetTeamStatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIGetTeamStatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIGetTeamStatsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIGetTeamStatsOK creates a OrgZalandoStupsPieroneAPIGetTeamStatsOK with default headers values
func NewOrgZalandoStupsPieroneAPIGetTeamStatsOK() *OrgZalandoStupsPieroneAPIGetTeamStatsOK {
	return &OrgZalandoStupsPieroneAPIGetTeamStatsOK{}
}

/*OrgZalandoStupsPieroneAPIGetTeamStatsOK handles this case with default header values.

Return team stats
*/
type OrgZalandoStupsPieroneAPIGetTeamStatsOK struct {
	Payload []*models.TeamStatistic
}

func (o *OrgZalandoStupsPieroneAPIGetTeamStatsOK) Error() string {
	return fmt.Sprintf("[GET /stats/teams/{team}][%d] orgZalandoStupsPieroneApiGetTeamStatsOK  %+v", 200, o.Payload)
}

func (o *OrgZalandoStupsPieroneAPIGetTeamStatsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
