package pier_one_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsPieroneAPIReadTeamsReader is a Reader for the OrgZalandoStupsPieroneAPIReadTeams structure.
type OrgZalandoStupsPieroneAPIReadTeamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsPieroneAPIReadTeamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOrgZalandoStupsPieroneAPIReadTeamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgZalandoStupsPieroneAPIReadTeamsOK creates a OrgZalandoStupsPieroneAPIReadTeamsOK with default headers values
func NewOrgZalandoStupsPieroneAPIReadTeamsOK() *OrgZalandoStupsPieroneAPIReadTeamsOK {
	return &OrgZalandoStupsPieroneAPIReadTeamsOK{}
}

/*OrgZalandoStupsPieroneAPIReadTeamsOK handles this case with default header values.

Return list of team IDs
*/
type OrgZalandoStupsPieroneAPIReadTeamsOK struct {
	Payload []string
}

func (o *OrgZalandoStupsPieroneAPIReadTeamsOK) Error() string {
	return fmt.Sprintf("[GET /teams][%d] orgZalandoStupsPieroneApiReadTeamsOK  %+v", 200, o.Payload)
}

func (o *OrgZalandoStupsPieroneAPIReadTeamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
