package pier_one_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgZalandoStupsPieroneAPIListTagsForImageParams creates a new OrgZalandoStupsPieroneAPIListTagsForImageParams object
// with the default values initialized.
func NewOrgZalandoStupsPieroneAPIListTagsForImageParams() *OrgZalandoStupsPieroneAPIListTagsForImageParams {
	var ()
	return &OrgZalandoStupsPieroneAPIListTagsForImageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgZalandoStupsPieroneAPIListTagsForImageParamsWithTimeout creates a new OrgZalandoStupsPieroneAPIListTagsForImageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgZalandoStupsPieroneAPIListTagsForImageParamsWithTimeout(timeout time.Duration) *OrgZalandoStupsPieroneAPIListTagsForImageParams {
	var ()
	return &OrgZalandoStupsPieroneAPIListTagsForImageParams{

		timeout: timeout,
	}
}

/*OrgZalandoStupsPieroneAPIListTagsForImageParams contains all the parameters to send to the API endpoint
for the org zalando stups pierone api list tags for image operation typically these are written to a http.Request
*/
type OrgZalandoStupsPieroneAPIListTagsForImageParams struct {

	/*Image*/
	Image string

	timeout time.Duration
}

// WithImage adds the image to the org zalando stups pierone api list tags for image params
func (o *OrgZalandoStupsPieroneAPIListTagsForImageParams) WithImage(image string) *OrgZalandoStupsPieroneAPIListTagsForImageParams {
	o.Image = image
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *OrgZalandoStupsPieroneAPIListTagsForImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param image
	if err := r.SetPathParam("image", o.Image); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
