package pier_one_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgZalandoStupsPieroneAPIGetScmSourceParams creates a new OrgZalandoStupsPieroneAPIGetScmSourceParams object
// with the default values initialized.
func NewOrgZalandoStupsPieroneAPIGetScmSourceParams() *OrgZalandoStupsPieroneAPIGetScmSourceParams {
	var ()
	return &OrgZalandoStupsPieroneAPIGetScmSourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgZalandoStupsPieroneAPIGetScmSourceParamsWithTimeout creates a new OrgZalandoStupsPieroneAPIGetScmSourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgZalandoStupsPieroneAPIGetScmSourceParamsWithTimeout(timeout time.Duration) *OrgZalandoStupsPieroneAPIGetScmSourceParams {
	var ()
	return &OrgZalandoStupsPieroneAPIGetScmSourceParams{

		timeout: timeout,
	}
}

/*OrgZalandoStupsPieroneAPIGetScmSourceParams contains all the parameters to send to the API endpoint
for the org zalando stups pierone api get scm source operation typically these are written to a http.Request
*/
type OrgZalandoStupsPieroneAPIGetScmSourceParams struct {

	/*Artifact*/
	Artifact string
	/*Tag*/
	Tag string
	/*Team*/
	Team string

	timeout time.Duration
}

// WithArtifact adds the artifact to the org zalando stups pierone api get scm source params
func (o *OrgZalandoStupsPieroneAPIGetScmSourceParams) WithArtifact(artifact string) *OrgZalandoStupsPieroneAPIGetScmSourceParams {
	o.Artifact = artifact
	return o
}

// WithTag adds the tag to the org zalando stups pierone api get scm source params
func (o *OrgZalandoStupsPieroneAPIGetScmSourceParams) WithTag(tag string) *OrgZalandoStupsPieroneAPIGetScmSourceParams {
	o.Tag = tag
	return o
}

// WithTeam adds the team to the org zalando stups pierone api get scm source params
func (o *OrgZalandoStupsPieroneAPIGetScmSourceParams) WithTeam(team string) *OrgZalandoStupsPieroneAPIGetScmSourceParams {
	o.Team = team
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *OrgZalandoStupsPieroneAPIGetScmSourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param artifact
	if err := r.SetPathParam("artifact", o.Artifact); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
