package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIParams creates a new OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIParams object
// with the default values initialized.
func NewOrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIParams() *OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIParams {

	return &OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIParamsWithTimeout creates a new OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIParamsWithTimeout(timeout time.Duration) *OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIParams {

	return &OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIParams{

		timeout: timeout,
	}
}

/*OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIParams contains all the parameters to send to the API endpoint
for the org zalando stups friboo system http redirect to swagger ui operation typically these are written to a http.Request
*/
type OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIParams struct {
	timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
