package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIReader is a Reader for the OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUI structure.
type OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewOrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewOrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIDefault creates a OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIDefault with default headers values
func NewOrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIDefault(code int) *OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIDefault {
	return &OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIDefault{
		_statusCode: code,
	}
}

/*OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIDefault handles this case with default header values.

Redirects to /ui/
*/
type OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIDefault struct {
	_statusCode int
}

// Code gets the status code for the org zalando stups friboo system http redirect to swagger ui default response
func (o *OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIDefault) Code() int {
	return o._statusCode
}

func (o *OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIDefault) Error() string {
	return fmt.Sprintf("[GET /][%d] org.zalando.stups.friboo.system.http/redirect-to-swagger-ui default ", o._statusCode)
}

func (o *OrgZalandoStupsFribooSystemHTTPRedirectToSwaggerUIDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
