package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*TagInformation tag information

swagger:model TagInformation
*/
type TagInformation struct {

	/* artifact
	 */
	Artifact string `json:"artifact,omitempty"`

	/* name
	 */
	Name string `json:"name,omitempty"`

	/* team
	 */
	Team string `json:"team,omitempty"`
}

// Validate validates this tag information
func (m *TagInformation) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
