package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*TagSummary tag summary

swagger:model TagSummary
*/
type TagSummary struct {

	/* clair id
	 */
	ClairID string `json:"clair_id,omitempty"`

	/* created
	 */
	Created string `json:"created,omitempty"`

	/* created by
	 */
	CreatedBy string `json:"created_by,omitempty"`

	/* image
	 */
	Image string `json:"image,omitempty"`

	/* name
	 */
	Name string `json:"name,omitempty"`

	/* severity fix available
	 */
	SeverityFixAvailable string `json:"severity_fix_available,omitempty"`

	/* severity no fix available
	 */
	SeverityNoFixAvailable string `json:"severity_no_fix_available,omitempty"`
}

// Validate validates this tag summary
func (m *TagSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
