package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*TeamStatistic team statistic

swagger:model TeamStatistic
*/
type TeamStatistic struct {

	/* artifacts
	 */
	Artifacts int64 `json:"artifacts,omitempty"`

	/* tags
	 */
	Tags int64 `json:"tags,omitempty"`
}

// Validate validates this team statistic
func (m *TeamStatistic) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
